/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.radm.jcalc;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        Calculator calculator = new Calculator();

        while (true) {
            System.out.println("Enter 'exit' to quit.");
            System.out.print("Enter an expression: ");
            String expression = scanner.nextLine();
            if (expression.equals("exit")) {
                break;
            }
            System.out.println(calculator.calculate(expression));
        }
        scanner.close();
    }
}
